// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Category struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type Course struct {
	ID         int32
	CategoryID int32
	Name       string
}
