### Test suceccessful
POST http://localhost:8080/weather HTTP/1.1
Content-Type: application/json

{
    "cep":"75915000" 
}


### Test invalid cep
POST http://localhost:8080/weather HTTP/1.1
Content-Type: application/json

{
    "cep":"75915-000" 
}

### Test invalid cep
POST http://localhost:8080/weather HTTP/1.1
Content-Type: application/json

{
    "cep":"75915" 
}

### Test invalid cep
POST http://localhost:8080/weather HTTP/1.1
Content-Type: application/json

{
    "cep":"7591500000" 
}

### Test cep not found
POST http://localhost:8080/weather HTTP/1.1
Content-Type: application/json

{
    "cep":"00000000" 
}