POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "My Product",
  "price": 100
}

###
GET http://localhost:8000/products/19c98096-55cc-44fa-b28d-5ed73c45f2d9
Content-Type: application/json

###
PUT http://localhost:8000/products/19c98096-55cc-44fa-b28d-5ed73c45f2d9
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 200
}

###
DELETE http://localhost:8000/products/19c98096-55cc-44fa-b28d-5ed73c45f2d9
Content-Type: application/json

###
GET http://localhost:8000/products
Authorization: Bearer <your_jwt_token>
Content-Type: application/json